
server:
  port: 8989
spring:
  kafka:
    producer:
      retries: 2
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    bootstrap-servers: 192.168.0.108:9092,192.168.0.138:9092,192.168.0.72:9092